// Code generated by sails-client-gen-v2. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct DiggerProxyClientProgram;

impl DiggerProxyClientProgram {
    pub const ROUTE_ID_DIGGER: u8 = 1;
}

impl sails_rs::client::Program for DiggerProxyClientProgram {}

pub trait DiggerProxyClient {
    type Env: sails_rs::client::GearEnv;
    fn digger(&self) -> sails_rs::client::Service<digger::DiggerImpl, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> DiggerProxyClient
    for sails_rs::client::Actor<DiggerProxyClientProgram, E>
{
    type Env = E;
    fn digger(&self) -> sails_rs::client::Service<digger::DiggerImpl, Self::Env> {
        self.service(DiggerProxyClientProgram::ROUTE_ID_DIGGER)
    }
}
pub trait DiggerProxyClientCtors {
    type Env: sails_rs::client::GearEnv;
    fn create(
        self,
        owner: ActorId,
        world: ActorId,
    ) -> sails_rs::client::PendingCtor<DiggerProxyClientProgram, io::Create, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> DiggerProxyClientCtors
    for sails_rs::client::Deployment<DiggerProxyClientProgram, E>
{
    type Env = E;
    fn create(
        self,
        owner: ActorId,
        world: ActorId,
    ) -> sails_rs::client::PendingCtor<DiggerProxyClientProgram, io::Create, Self::Env> {
        self.pending_ctor((owner, world))
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Create (owner: ActorId, world: ActorId) -> (), 0);
}

pub mod digger {
    use super::*;

    pub trait Digger {
        type Env: sails_rs::client::GearEnv;
        fn drill(&mut self, direction: u32) -> sails_rs::client::PendingCall<io::Drill, Self::Env>;
        fn exit(&mut self) -> sails_rs::client::PendingCall<io::Exit, Self::Env>;
        fn kill(
            &mut self,
            inheritor: ActorId,
        ) -> sails_rs::client::PendingCall<io::Kill, Self::Env>;
        fn last_message_id(&self) -> sails_rs::client::PendingCall<io::LastMessageId, Self::Env>;
        fn mint_resources(&mut self)
        -> sails_rs::client::PendingCall<io::MintResources, Self::Env>;
        fn move_agent(
            &mut self,
            direction: u32,
        ) -> sails_rs::client::PendingCall<io::MoveAgent, Self::Env>;
        fn owner(&self) -> sails_rs::client::PendingCall<io::Owner, Self::Env>;
        fn place_ladder(
            &mut self,
            direction: u32,
        ) -> sails_rs::client::PendingCall<io::PlaceLadder, Self::Env>;
        fn register(&mut self) -> sails_rs::client::PendingCall<io::Register, Self::Env>;
        fn set_world(
            &mut self,
            world: ActorId,
        ) -> sails_rs::client::PendingCall<io::SetWorld, Self::Env>;
        fn status(&self) -> sails_rs::client::PendingCall<io::Status, Self::Env>;
        fn surface(&mut self) -> sails_rs::client::PendingCall<io::Surface, Self::Env>;
        fn trade_resources_for_ladders(
            &mut self,
            scrst: u32,
            bcrst: u32,
            hcrst: u32,
        ) -> sails_rs::client::PendingCall<io::TradeResourcesForLadders, Self::Env>;
        fn world(&self) -> sails_rs::client::PendingCall<io::World, Self::Env>;
    }

    pub struct DiggerImpl;

    impl sails_rs::client::Identifiable for DiggerImpl {
        const INTERFACE_ID: sails_rs::InterfaceId =
            sails_rs::InterfaceId::from_bytes_8([156, 142, 81, 184, 133, 121, 7, 221]);
    }

    impl<E: sails_rs::client::GearEnv> Digger for sails_rs::client::Service<DiggerImpl, E> {
        type Env = E;
        fn drill(&mut self, direction: u32) -> sails_rs::client::PendingCall<io::Drill, Self::Env> {
            self.pending_call((direction,))
        }
        fn exit(&mut self) -> sails_rs::client::PendingCall<io::Exit, Self::Env> {
            self.pending_call(())
        }
        fn kill(
            &mut self,
            inheritor: ActorId,
        ) -> sails_rs::client::PendingCall<io::Kill, Self::Env> {
            self.pending_call((inheritor,))
        }
        fn last_message_id(&self) -> sails_rs::client::PendingCall<io::LastMessageId, Self::Env> {
            self.pending_call(())
        }
        fn mint_resources(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::MintResources, Self::Env> {
            self.pending_call(())
        }
        fn move_agent(
            &mut self,
            direction: u32,
        ) -> sails_rs::client::PendingCall<io::MoveAgent, Self::Env> {
            self.pending_call((direction,))
        }
        fn owner(&self) -> sails_rs::client::PendingCall<io::Owner, Self::Env> {
            self.pending_call(())
        }
        fn place_ladder(
            &mut self,
            direction: u32,
        ) -> sails_rs::client::PendingCall<io::PlaceLadder, Self::Env> {
            self.pending_call((direction,))
        }
        fn register(&mut self) -> sails_rs::client::PendingCall<io::Register, Self::Env> {
            self.pending_call(())
        }
        fn set_world(
            &mut self,
            world: ActorId,
        ) -> sails_rs::client::PendingCall<io::SetWorld, Self::Env> {
            self.pending_call((world,))
        }
        fn status(&self) -> sails_rs::client::PendingCall<io::Status, Self::Env> {
            self.pending_call(())
        }
        fn surface(&mut self) -> sails_rs::client::PendingCall<io::Surface, Self::Env> {
            self.pending_call(())
        }
        fn trade_resources_for_ladders(
            &mut self,
            scrst: u32,
            bcrst: u32,
            hcrst: u32,
        ) -> sails_rs::client::PendingCall<io::TradeResourcesForLadders, Self::Env> {
            self.pending_call((scrst, bcrst, hcrst))
        }
        fn world(&self) -> sails_rs::client::PendingCall<io::World, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(Drill (direction: u32) -> [u8; 32] | String, 0, <super::DiggerImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Exit () -> [u8; 32] | String, 1, <super::DiggerImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Kill (inheritor: ActorId) -> () | String, 2, <super::DiggerImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(LastMessageId () -> [u8; 32] | String, 3, <super::DiggerImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(MintResources () -> [u8; 32] | String, 4, <super::DiggerImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(MoveAgent (direction: u32) -> [u8; 32] | String, 5, <super::DiggerImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Owner () -> ActorId | String, 6, <super::DiggerImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(PlaceLadder (direction: u32) -> [u8; 32] | String, 7, <super::DiggerImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Register () -> [u8; 32] | String, 8, <super::DiggerImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(SetWorld (world: ActorId) -> ActorId | String, 9, <super::DiggerImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Status () -> Vec<u128> | String, 10, <super::DiggerImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Surface () -> [u8; 32] | String, 11, <super::DiggerImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(TradeResourcesForLadders (scrst: u32, bcrst: u32, hcrst: u32) -> [u8; 32] | String, 12, <super::DiggerImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(World () -> ActorId | String, 13, <super::DiggerImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[sails_rs::sails_type(crate = sails_rs)]
        #[derive(PartialEq, Debug)]
        pub enum DiggerEvents {
            #[codec(index = 0)]
            Forwarded(u64, u32, [u8; 32]),
            #[codec(index = 1)]
            Killed([u8; 32]),
            #[codec(index = 2)]
            WorldUpdated([u8; 32], [u8; 32]),
        }

        impl DiggerEvents {
            pub fn entry_id(&self) -> u16 {
                match self {
                    Self::Forwarded { .. } => 0,
                    Self::Killed { .. } => 1,
                    Self::WorldUpdated { .. } => 2,
                }
            }
        }

        impl sails_rs::client::Event for DiggerEvents {
            fn decode_event(
                route: &sails_rs::client::RouteIdx,
                payload: impl AsRef<[u8]>,
            ) -> Result<Self, sails_rs::scale_codec::Error> {
                sails_rs::client::decode_event_v2::<Self>(route.0, payload)
            }
        }

        impl sails_rs::client::Identifiable for DiggerEvents {
            const INTERFACE_ID: sails_rs::InterfaceId =
                <DiggerImpl as sails_rs::client::Identifiable>::INTERFACE_ID;
        }

        impl sails_rs::client::ServiceWithEvents for DiggerImpl {
            type Event = DiggerEvents;
        }
    }
}
