
!@sails: 1.0.0-beta.5

service Redeem@0x74c0432f9f172e15 {
    events {
        RedeemCanceled(u128, [u8; 32], u128, u128, u128, u128),
        Redeemed([u8; 32], u128, u128, u128, u128),
        RedeemRequested(u128, [u8; 32], u128, u128, u128, u128),
        ReserveDeposited([u8; 32], u128, u128),
        ReserveSynced(u128, u128),
    }
    functions {
        @query
        AvailableReserve() -> u128 throws String;
        @query
        BcrstRate() -> u128 throws String;
        CancelRedeem(redeem_id: u128) throws String;
        ConfirmRedeem(redeem_id: u128) -> u128 throws String;
        @payable
        DepositReserve() -> u128 throws String;
        @query
        HcrstRate() -> u128 throws String;
        @query
        LockedBalance() -> u128 throws String;
        @query
        PendingRedeemCount() -> u128 throws String;
        Redeem(scrst: u128, bcrst: u128, hcrst: u128) -> u128 throws String;
        @query
        ReserveBalance() -> u128 throws String;
        @query
        ScrstRate() -> u128 throws String;
        @query
        TotalPaid() -> u128 throws String;
        @query
        TotalRedeemedBcrst() -> u128 throws String;
        @query
        TotalRedeemedHcrst() -> u128 throws String;
        @query
        TotalRedeemedScrst() -> u128 throws String;
        @query
        VaraUnit() -> u128 throws String;
    }
}

service Admin@0x93ef6a6a3d7e1391 {
    events {
        AdminAdded([u8; 32]),
        AdminRemoved([u8; 32]),
        FundsWithdrawn([u8; 32], u128, u128),
        Paused([u8; 32]),
        PendingRedeemForceCanceled(u128, [u8; 32], u128, u128, u128, u128),
        PendingRedeemForcePaid(u128, [u8; 32], u128, u128, u128, u128),
        RateConfigUpdated(u128, u128, u128, u128),
        RatesUpdated(u128, u128, u128),
        ResContractUpdated([u8; 32], [u8; 32]),
        Unpaused([u8; 32]),
    }
    functions {
        AddAdmin(admin: ActorId) -> bool throws String;
        @query
        Admins() -> [ActorId] throws String;
        ForceCancelRedeem(redeem_id: u128) throws String;
        @returns_value
        ForcePayRedeem(redeem_id: u128) throws String;
        @query
        IsAdmin(account: ActorId) -> bool throws String;
        @query
        IsPaused() -> bool throws String;
        Pause() throws String;
        RemoveAdmin(admin: ActorId) -> bool throws String;
        @query
        ResContract() -> ActorId throws String;
        SetRateConfig(vara_unit: u128, scrst_rate: u128, bcrst_rate: u128, hcrst_rate: u128) throws String;
        SetRates(scrst_rate: u128, bcrst_rate: u128, hcrst_rate: u128) throws String;
        SetResContract(res_contract: ActorId) throws String;
        Unpause() throws String;
        @returns_value
        WithdrawFunds(amount: u128) throws String;
    }
}

program DiggerRedeem {
    constructors {
        Create(res_contract: ActorId, vara_unit: u128, scrst_rate: u128, bcrst_rate: u128, hcrst_rate: u128);
    }
    services {
        Redeem@0x74c0432f9f172e15,
        Admin@0x93ef6a6a3d7e1391,
    }
}
