// Code generated by sails-client-gen-v2. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct DiggerWorldClientProgram;

impl DiggerWorldClientProgram {
    pub const ROUTE_ID_WORLD: u8 = 1;
    pub const ROUTE_ID_ADMIN: u8 = 2;
}

impl sails_rs::client::Program for DiggerWorldClientProgram {}

pub trait DiggerWorldClient {
    type Env: sails_rs::client::GearEnv;
    fn world(&self) -> sails_rs::client::Service<world::WorldImpl, Self::Env>;
    fn admin(&self) -> sails_rs::client::Service<admin::AdminImpl, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> DiggerWorldClient
    for sails_rs::client::Actor<DiggerWorldClientProgram, E>
{
    type Env = E;
    fn world(&self) -> sails_rs::client::Service<world::WorldImpl, Self::Env> {
        self.service(DiggerWorldClientProgram::ROUTE_ID_WORLD)
    }
    fn admin(&self) -> sails_rs::client::Service<admin::AdminImpl, Self::Env> {
        self.service(DiggerWorldClientProgram::ROUTE_ID_ADMIN)
    }
}
pub trait DiggerWorldClientCtors {
    type Env: sails_rs::client::GearEnv;
    fn create(
        self,
        config: (
            (u32, u32, u32, u32, u32, u32, u32, u32, u32, u32),
            (u32, u32, u32, u32, u32, u32),
        ),
    ) -> sails_rs::client::PendingCtor<DiggerWorldClientProgram, io::Create, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> DiggerWorldClientCtors
    for sails_rs::client::Deployment<DiggerWorldClientProgram, E>
{
    type Env = E;
    fn create(
        self,
        config: (
            (u32, u32, u32, u32, u32, u32, u32, u32, u32, u32),
            (u32, u32, u32, u32, u32, u32),
        ),
    ) -> sails_rs::client::PendingCtor<DiggerWorldClientProgram, io::Create, Self::Env> {
        self.pending_ctor((config,))
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Create (config: ((u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, ), (u32, u32, u32, u32, u32, u32, ), )) -> (), 0);
}

pub mod world {
    use super::*;

    pub trait World {
        type Env: sails_rs::client::GearEnv;
        fn agent_of(&self, owner: ActorId)
        -> sails_rs::client::PendingCall<io::AgentOf, Self::Env>;
        fn agents(&self) -> sails_rs::client::PendingCall<io::Agents, Self::Env>;
        fn config(&self) -> sails_rs::client::PendingCall<io::Config, Self::Env>;
        fn drill(&mut self, direction: u32) -> sails_rs::client::PendingCall<io::Drill, Self::Env>;
        fn exit(&mut self) -> sails_rs::client::PendingCall<io::Exit, Self::Env>;
        fn inventory_of(
            &self,
            owner: ActorId,
        ) -> sails_rs::client::PendingCall<io::InventoryOf, Self::Env>;
        fn is_dug(&self, x: u32, y: u32) -> sails_rs::client::PendingCall<io::IsDug, Self::Env>;
        fn map_snapshot(&self) -> sails_rs::client::PendingCall<io::MapSnapshot, Self::Env>;
        fn mint_resources(&mut self)
        -> sails_rs::client::PendingCall<io::MintResources, Self::Env>;
        fn move_agent(
            &mut self,
            direction: u32,
        ) -> sails_rs::client::PendingCall<io::MoveAgent, Self::Env>;
        fn owner_of(&self, proxy: ActorId)
        -> sails_rs::client::PendingCall<io::OwnerOf, Self::Env>;
        fn place_ladder(
            &mut self,
            direction: u32,
        ) -> sails_rs::client::PendingCall<io::PlaceLadder, Self::Env>;
        fn register(
            &mut self,
            owner: ActorId,
        ) -> sails_rs::client::PendingCall<io::Register, Self::Env>;
        fn session(&self) -> sails_rs::client::PendingCall<io::Session, Self::Env>;
        fn surface(&mut self) -> sails_rs::client::PendingCall<io::Surface, Self::Env>;
        fn tile_at(&self, x: u32, y: u32) -> sails_rs::client::PendingCall<io::TileAt, Self::Env>;
        fn trade_resources_for_ladders(
            &mut self,
            scrst: u32,
            bcrst: u32,
            hcrst: u32,
        ) -> sails_rs::client::PendingCall<io::TradeResourcesForLadders, Self::Env>;
    }

    pub struct WorldImpl;

    impl sails_rs::client::Identifiable for WorldImpl {
        const INTERFACE_ID: sails_rs::InterfaceId =
            sails_rs::InterfaceId::from_bytes_8([198, 51, 16, 215, 112, 6, 233, 13]);
    }

    impl<E: sails_rs::client::GearEnv> World for sails_rs::client::Service<WorldImpl, E> {
        type Env = E;
        fn agent_of(
            &self,
            owner: ActorId,
        ) -> sails_rs::client::PendingCall<io::AgentOf, Self::Env> {
            self.pending_call((owner,))
        }
        fn agents(&self) -> sails_rs::client::PendingCall<io::Agents, Self::Env> {
            self.pending_call(())
        }
        fn config(&self) -> sails_rs::client::PendingCall<io::Config, Self::Env> {
            self.pending_call(())
        }
        fn drill(&mut self, direction: u32) -> sails_rs::client::PendingCall<io::Drill, Self::Env> {
            self.pending_call((direction,))
        }
        fn exit(&mut self) -> sails_rs::client::PendingCall<io::Exit, Self::Env> {
            self.pending_call(())
        }
        fn inventory_of(
            &self,
            owner: ActorId,
        ) -> sails_rs::client::PendingCall<io::InventoryOf, Self::Env> {
            self.pending_call((owner,))
        }
        fn is_dug(&self, x: u32, y: u32) -> sails_rs::client::PendingCall<io::IsDug, Self::Env> {
            self.pending_call((x, y))
        }
        fn map_snapshot(&self) -> sails_rs::client::PendingCall<io::MapSnapshot, Self::Env> {
            self.pending_call(())
        }
        fn mint_resources(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::MintResources, Self::Env> {
            self.pending_call(())
        }
        fn move_agent(
            &mut self,
            direction: u32,
        ) -> sails_rs::client::PendingCall<io::MoveAgent, Self::Env> {
            self.pending_call((direction,))
        }
        fn owner_of(
            &self,
            proxy: ActorId,
        ) -> sails_rs::client::PendingCall<io::OwnerOf, Self::Env> {
            self.pending_call((proxy,))
        }
        fn place_ladder(
            &mut self,
            direction: u32,
        ) -> sails_rs::client::PendingCall<io::PlaceLadder, Self::Env> {
            self.pending_call((direction,))
        }
        fn register(
            &mut self,
            owner: ActorId,
        ) -> sails_rs::client::PendingCall<io::Register, Self::Env> {
            self.pending_call((owner,))
        }
        fn session(&self) -> sails_rs::client::PendingCall<io::Session, Self::Env> {
            self.pending_call(())
        }
        fn surface(&mut self) -> sails_rs::client::PendingCall<io::Surface, Self::Env> {
            self.pending_call(())
        }
        fn tile_at(&self, x: u32, y: u32) -> sails_rs::client::PendingCall<io::TileAt, Self::Env> {
            self.pending_call((x, y))
        }
        fn trade_resources_for_ladders(
            &mut self,
            scrst: u32,
            bcrst: u32,
            hcrst: u32,
        ) -> sails_rs::client::PendingCall<io::TradeResourcesForLadders, Self::Env> {
            self.pending_call((scrst, bcrst, hcrst))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(AgentOf (owner: ActorId) -> Vec<u128> | String, 0, <super::WorldImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Agents () -> Vec<ActorId> | String, 1, <super::WorldImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Config () -> Vec<u32> | String, 2, <super::WorldImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Drill (direction: u32) -> Vec<u128> | String, 3, <super::WorldImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Exit () -> Vec<u128> | String, 4, <super::WorldImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(InventoryOf (owner: ActorId) -> Vec<u32> | String, 5, <super::WorldImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(IsDug (x: u32, y: u32) -> bool | String, 6, <super::WorldImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(MapSnapshot () -> Vec<u32> | String, 7, <super::WorldImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(MintResources () -> Vec<u128> | String, 8, <super::WorldImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(MoveAgent (direction: u32) -> Vec<u128> | String, 9, <super::WorldImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(OwnerOf (proxy: ActorId) -> ActorId | String, 10, <super::WorldImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(PlaceLadder (direction: u32) -> Vec<u128> | String, 11, <super::WorldImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Register (owner: ActorId) -> Vec<u128> | String, 12, <super::WorldImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Session () -> Vec<u128> | String, 13, <super::WorldImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Surface () -> Vec<u128> | String, 14, <super::WorldImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(TileAt (x: u32, y: u32) -> u32 | String, 15, <super::WorldImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(TradeResourcesForLadders (scrst: u32, bcrst: u32, hcrst: u32) -> Vec<u128> | String, 16, <super::WorldImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[sails_rs::sails_type(crate = sails_rs)]
        #[derive(PartialEq, Debug)]
        pub enum WorldEvents {
            #[codec(index = 0)]
            AgentDied(u64, [u8; 32], u32, u32, u32),
            #[codec(index = 1)]
            AgentExited(u64, [u8; 32]),
            #[codec(index = 2)]
            AgentMoved(u64, [u8; 32], u32, u32, u32, u32),
            #[codec(index = 3)]
            AgentRegistered(u64, [u8; 32]),
            #[codec(index = 4)]
            AgentSpawned(u64, [u8; 32], u32, u32),
            #[codec(index = 5)]
            AgentSurfaced(u64, [u8; 32], u32, u32, u32),
            #[codec(index = 6)]
            ChestOpened(u64, [u8; 32], u32, u32, u32, u32),
            #[codec(index = 7)]
            LadderPlaced(u64, [u8; 32], u32, u32, u32),
            #[codec(index = 8)]
            ResourceExtracted(u64, [u8; 32], u32, u32, u32, u32),
            #[codec(index = 9)]
            ResourcesMinted(u64, [u8; 32], u32, u32, u32),
            #[codec(index = 10)]
            ResourcesTradedForLadders(u64, [u8; 32], u32, u32, u32, u32, u32),
            #[codec(index = 11)]
            SessionStarted(u64),
            #[codec(index = 12)]
            StoneMoved(u64, [u8; 32], u32, u32, u32, u32),
            #[codec(index = 13)]
            TileDrilled(u64, [u8; 32], u32, u32, u32, u32),
        }

        impl WorldEvents {
            pub fn entry_id(&self) -> u16 {
                match self {
                    Self::AgentDied { .. } => 0,
                    Self::AgentExited { .. } => 1,
                    Self::AgentMoved { .. } => 2,
                    Self::AgentRegistered { .. } => 3,
                    Self::AgentSpawned { .. } => 4,
                    Self::AgentSurfaced { .. } => 5,
                    Self::ChestOpened { .. } => 6,
                    Self::LadderPlaced { .. } => 7,
                    Self::ResourceExtracted { .. } => 8,
                    Self::ResourcesMinted { .. } => 9,
                    Self::ResourcesTradedForLadders { .. } => 10,
                    Self::SessionStarted { .. } => 11,
                    Self::StoneMoved { .. } => 12,
                    Self::TileDrilled { .. } => 13,
                }
            }
        }

        impl sails_rs::client::Event for WorldEvents {
            fn decode_event(
                route: &sails_rs::client::RouteIdx,
                payload: impl AsRef<[u8]>,
            ) -> Result<Self, sails_rs::scale_codec::Error> {
                sails_rs::client::decode_event_v2::<Self>(route.0, payload)
            }
        }

        impl sails_rs::client::Identifiable for WorldEvents {
            const INTERFACE_ID: sails_rs::InterfaceId =
                <WorldImpl as sails_rs::client::Identifiable>::INTERFACE_ID;
        }

        impl sails_rs::client::ServiceWithEvents for WorldImpl {
            type Event = WorldEvents;
        }
    }
}

pub mod admin {
    use super::*;

    pub trait Admin {
        type Env: sails_rs::client::GearEnv;
        fn admin(&self) -> sails_rs::client::PendingCall<io::Admin, Self::Env>;
        fn chest_dynamite_chance_bps(
            &self,
        ) -> sails_rs::client::PendingCall<io::ChestDynamiteChanceBps, Self::Env>;
        fn finish_session(&mut self)
        -> sails_rs::client::PendingCall<io::FinishSession, Self::Env>;
        fn kill(
            &mut self,
            inheritor: ActorId,
        ) -> sails_rs::client::PendingCall<io::Kill, Self::Env>;
        fn ladder_exchange_rate(
            &self,
        ) -> sails_rs::client::PendingCall<io::LadderExchangeRate, Self::Env>;
        fn reset_map(
            &mut self,
            seed: u64,
        ) -> sails_rs::client::PendingCall<io::ResetMap, Self::Env>;
        fn resource_vmt(&self) -> sails_rs::client::PendingCall<io::ResourceVmt, Self::Env>;
        fn set_chest_dynamite_chance_bps(
            &mut self,
            chest_dynamite_chance_bps: u32,
        ) -> sails_rs::client::PendingCall<io::SetChestDynamiteChanceBps, Self::Env>;
        fn set_ladder_exchange_rate(
            &mut self,
            ladder_scrst_resource_amount: u32,
            ladder_scrst_ladder_amount: u32,
            ladder_bcrst_resource_amount: u32,
            ladder_bcrst_ladder_amount: u32,
            ladder_hcrst_resource_amount: u32,
            ladder_hcrst_ladder_amount: u32,
        ) -> sails_rs::client::PendingCall<io::SetLadderExchangeRate, Self::Env>;
        fn set_resource_vmt(
            &mut self,
            resource_vmt: ActorId,
        ) -> sails_rs::client::PendingCall<io::SetResourceVmt, Self::Env>;
        fn start_session(&mut self) -> sails_rs::client::PendingCall<io::StartSession, Self::Env>;
        fn upload_map(
            &mut self,
            seed: u64,
            map: Vec<u32>,
        ) -> sails_rs::client::PendingCall<io::UploadMap, Self::Env>;
    }

    pub struct AdminImpl;

    impl sails_rs::client::Identifiable for AdminImpl {
        const INTERFACE_ID: sails_rs::InterfaceId =
            sails_rs::InterfaceId::from_bytes_8([4, 211, 146, 145, 149, 160, 122, 21]);
    }

    impl<E: sails_rs::client::GearEnv> Admin for sails_rs::client::Service<AdminImpl, E> {
        type Env = E;
        fn admin(&self) -> sails_rs::client::PendingCall<io::Admin, Self::Env> {
            self.pending_call(())
        }
        fn chest_dynamite_chance_bps(
            &self,
        ) -> sails_rs::client::PendingCall<io::ChestDynamiteChanceBps, Self::Env> {
            self.pending_call(())
        }
        fn finish_session(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::FinishSession, Self::Env> {
            self.pending_call(())
        }
        fn kill(
            &mut self,
            inheritor: ActorId,
        ) -> sails_rs::client::PendingCall<io::Kill, Self::Env> {
            self.pending_call((inheritor,))
        }
        fn ladder_exchange_rate(
            &self,
        ) -> sails_rs::client::PendingCall<io::LadderExchangeRate, Self::Env> {
            self.pending_call(())
        }
        fn reset_map(
            &mut self,
            seed: u64,
        ) -> sails_rs::client::PendingCall<io::ResetMap, Self::Env> {
            self.pending_call((seed,))
        }
        fn resource_vmt(&self) -> sails_rs::client::PendingCall<io::ResourceVmt, Self::Env> {
            self.pending_call(())
        }
        fn set_chest_dynamite_chance_bps(
            &mut self,
            chest_dynamite_chance_bps: u32,
        ) -> sails_rs::client::PendingCall<io::SetChestDynamiteChanceBps, Self::Env> {
            self.pending_call((chest_dynamite_chance_bps,))
        }
        fn set_ladder_exchange_rate(
            &mut self,
            ladder_scrst_resource_amount: u32,
            ladder_scrst_ladder_amount: u32,
            ladder_bcrst_resource_amount: u32,
            ladder_bcrst_ladder_amount: u32,
            ladder_hcrst_resource_amount: u32,
            ladder_hcrst_ladder_amount: u32,
        ) -> sails_rs::client::PendingCall<io::SetLadderExchangeRate, Self::Env> {
            self.pending_call((
                ladder_scrst_resource_amount,
                ladder_scrst_ladder_amount,
                ladder_bcrst_resource_amount,
                ladder_bcrst_ladder_amount,
                ladder_hcrst_resource_amount,
                ladder_hcrst_ladder_amount,
            ))
        }
        fn set_resource_vmt(
            &mut self,
            resource_vmt: ActorId,
        ) -> sails_rs::client::PendingCall<io::SetResourceVmt, Self::Env> {
            self.pending_call((resource_vmt,))
        }
        fn start_session(&mut self) -> sails_rs::client::PendingCall<io::StartSession, Self::Env> {
            self.pending_call(())
        }
        fn upload_map(
            &mut self,
            seed: u64,
            map: Vec<u32>,
        ) -> sails_rs::client::PendingCall<io::UploadMap, Self::Env> {
            self.pending_call((seed, map))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(Admin () -> ActorId | String, 0, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(ChestDynamiteChanceBps () -> u32 | String, 1, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(FinishSession () -> Vec<u128> | String, 2, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Kill (inheritor: ActorId) -> () | String, 3, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(LadderExchangeRate () -> Vec<u32> | String, 4, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(ResetMap (seed: u64) -> Vec<u128> | String, 5, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(ResourceVmt () -> ActorId | String, 6, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(SetChestDynamiteChanceBps (chest_dynamite_chance_bps: u32) -> u32 | String, 7, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(SetLadderExchangeRate (ladder_scrst_resource_amount: u32, ladder_scrst_ladder_amount: u32, ladder_bcrst_resource_amount: u32, ladder_bcrst_ladder_amount: u32, ladder_hcrst_resource_amount: u32, ladder_hcrst_ladder_amount: u32) -> Vec<u32> | String, 8, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(SetResourceVmt (resource_vmt: ActorId) -> ActorId | String, 9, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(StartSession () -> Vec<u128> | String, 10, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(UploadMap (seed: u64, map: Vec<u32>) -> Vec<u128> | String, 11, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[sails_rs::sails_type(crate = sails_rs)]
        #[derive(PartialEq, Debug)]
        pub enum AdminEvents {
            #[codec(index = 0)]
            Killed([u8; 32]),
            #[codec(index = 1)]
            MapGenerated(u64, u64),
            #[codec(index = 2)]
            ResourceVmtUpdated([u8; 32], [u8; 32]),
            #[codec(index = 3)]
            SessionFinished(u64),
            #[codec(index = 4)]
            SessionStarted(u64),
        }

        impl AdminEvents {
            pub fn entry_id(&self) -> u16 {
                match self {
                    Self::Killed { .. } => 0,
                    Self::MapGenerated { .. } => 1,
                    Self::ResourceVmtUpdated { .. } => 2,
                    Self::SessionFinished { .. } => 3,
                    Self::SessionStarted { .. } => 4,
                }
            }
        }

        impl sails_rs::client::Event for AdminEvents {
            fn decode_event(
                route: &sails_rs::client::RouteIdx,
                payload: impl AsRef<[u8]>,
            ) -> Result<Self, sails_rs::scale_codec::Error> {
                sails_rs::client::decode_event_v2::<Self>(route.0, payload)
            }
        }

        impl sails_rs::client::Identifiable for AdminEvents {
            const INTERFACE_ID: sails_rs::InterfaceId =
                <AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID;
        }

        impl sails_rs::client::ServiceWithEvents for AdminImpl {
            type Event = AdminEvents;
        }
    }
}
