// Code generated by sails-client-gen-v2. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct DiggerResVmtClientProgram;

impl DiggerResVmtClientProgram {
    pub const ROUTE_ID_VMT: u8 = 1;
    pub const ROUTE_ID_ADMIN: u8 = 2;
}

impl sails_rs::client::Program for DiggerResVmtClientProgram {}

pub trait DiggerResVmtClient {
    type Env: sails_rs::client::GearEnv;
    fn vmt(&self) -> sails_rs::client::Service<vmt::VmtImpl, Self::Env>;
    fn admin(&self) -> sails_rs::client::Service<admin::AdminImpl, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> DiggerResVmtClient
    for sails_rs::client::Actor<DiggerResVmtClientProgram, E>
{
    type Env = E;
    fn vmt(&self) -> sails_rs::client::Service<vmt::VmtImpl, Self::Env> {
        self.service(DiggerResVmtClientProgram::ROUTE_ID_VMT)
    }
    fn admin(&self) -> sails_rs::client::Service<admin::AdminImpl, Self::Env> {
        self.service(DiggerResVmtClientProgram::ROUTE_ID_ADMIN)
    }
}
pub trait DiggerResVmtClientCtors {
    type Env: sails_rs::client::GearEnv;
    fn create(
        self,
        redeem_contract: ActorId,
        minter: ActorId,
    ) -> sails_rs::client::PendingCtor<DiggerResVmtClientProgram, io::Create, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> DiggerResVmtClientCtors
    for sails_rs::client::Deployment<DiggerResVmtClientProgram, E>
{
    type Env = E;
    fn create(
        self,
        redeem_contract: ActorId,
        minter: ActorId,
    ) -> sails_rs::client::PendingCtor<DiggerResVmtClientProgram, io::Create, Self::Env> {
        self.pending_ctor((redeem_contract, minter))
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Create (redeem_contract: ActorId, minter: ActorId) -> (), 0);
}

pub mod vmt {
    use super::*;

    pub trait Vmt {
        type Env: sails_rs::client::GearEnv;
        fn approve(
            &mut self,
            operator: ActorId,
        ) -> sails_rs::client::PendingCall<io::Approve, Self::Env>;
        fn balance_of(
            &self,
            account: ActorId,
            id: u128,
        ) -> sails_rs::client::PendingCall<io::BalanceOf, Self::Env>;
        fn batch_transfer_from(
            &mut self,
            from: ActorId,
            to: ActorId,
            ids: Vec<u128>,
            amounts: Vec<u128>,
        ) -> sails_rs::client::PendingCall<io::BatchTransferFrom, Self::Env>;
        fn bcrst_token_id(&self) -> sails_rs::client::PendingCall<io::BcrstTokenId, Self::Env>;
        fn burn_for_redeem(
            &mut self,
            redeem_id: u128,
            owner: ActorId,
            scrst: u128,
            bcrst: u128,
            hcrst: u128,
        ) -> sails_rs::client::PendingCall<io::BurnForRedeem, Self::Env>;
        fn decimals(&self) -> sails_rs::client::PendingCall<io::Decimals, Self::Env>;
        fn hcrst_token_id(&self) -> sails_rs::client::PendingCall<io::HcrstTokenId, Self::Env>;
        fn is_approved(
            &self,
            account: ActorId,
            operator: ActorId,
        ) -> sails_rs::client::PendingCall<io::IsApproved, Self::Env>;
        fn mint_resources(
            &mut self,
            to: ActorId,
            scrst: u128,
            bcrst: u128,
            hcrst: u128,
        ) -> sails_rs::client::PendingCall<io::MintResources, Self::Env>;
        fn name(&self) -> sails_rs::client::PendingCall<io::Name, Self::Env>;
        fn scrst_token_id(&self) -> sails_rs::client::PendingCall<io::ScrstTokenId, Self::Env>;
        fn symbol(&self) -> sails_rs::client::PendingCall<io::Symbol, Self::Env>;
        fn total_supply_of(
            &self,
            id: u128,
        ) -> sails_rs::client::PendingCall<io::TotalSupplyOf, Self::Env>;
        fn transfer_from(
            &mut self,
            from: ActorId,
            to: ActorId,
            id: u128,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::TransferFrom, Self::Env>;
    }

    pub struct VmtImpl;

    impl sails_rs::client::Identifiable for VmtImpl {
        const INTERFACE_ID: sails_rs::InterfaceId =
            sails_rs::InterfaceId::from_bytes_8([78, 1, 228, 221, 128, 109, 82, 187]);
    }

    impl<E: sails_rs::client::GearEnv> Vmt for sails_rs::client::Service<VmtImpl, E> {
        type Env = E;
        fn approve(
            &mut self,
            operator: ActorId,
        ) -> sails_rs::client::PendingCall<io::Approve, Self::Env> {
            self.pending_call((operator,))
        }
        fn balance_of(
            &self,
            account: ActorId,
            id: u128,
        ) -> sails_rs::client::PendingCall<io::BalanceOf, Self::Env> {
            self.pending_call((account, id))
        }
        fn batch_transfer_from(
            &mut self,
            from: ActorId,
            to: ActorId,
            ids: Vec<u128>,
            amounts: Vec<u128>,
        ) -> sails_rs::client::PendingCall<io::BatchTransferFrom, Self::Env> {
            self.pending_call((from, to, ids, amounts))
        }
        fn bcrst_token_id(&self) -> sails_rs::client::PendingCall<io::BcrstTokenId, Self::Env> {
            self.pending_call(())
        }
        fn burn_for_redeem(
            &mut self,
            redeem_id: u128,
            owner: ActorId,
            scrst: u128,
            bcrst: u128,
            hcrst: u128,
        ) -> sails_rs::client::PendingCall<io::BurnForRedeem, Self::Env> {
            self.pending_call((redeem_id, owner, scrst, bcrst, hcrst))
        }
        fn decimals(&self) -> sails_rs::client::PendingCall<io::Decimals, Self::Env> {
            self.pending_call(())
        }
        fn hcrst_token_id(&self) -> sails_rs::client::PendingCall<io::HcrstTokenId, Self::Env> {
            self.pending_call(())
        }
        fn is_approved(
            &self,
            account: ActorId,
            operator: ActorId,
        ) -> sails_rs::client::PendingCall<io::IsApproved, Self::Env> {
            self.pending_call((account, operator))
        }
        fn mint_resources(
            &mut self,
            to: ActorId,
            scrst: u128,
            bcrst: u128,
            hcrst: u128,
        ) -> sails_rs::client::PendingCall<io::MintResources, Self::Env> {
            self.pending_call((to, scrst, bcrst, hcrst))
        }
        fn name(&self) -> sails_rs::client::PendingCall<io::Name, Self::Env> {
            self.pending_call(())
        }
        fn scrst_token_id(&self) -> sails_rs::client::PendingCall<io::ScrstTokenId, Self::Env> {
            self.pending_call(())
        }
        fn symbol(&self) -> sails_rs::client::PendingCall<io::Symbol, Self::Env> {
            self.pending_call(())
        }
        fn total_supply_of(
            &self,
            id: u128,
        ) -> sails_rs::client::PendingCall<io::TotalSupplyOf, Self::Env> {
            self.pending_call((id,))
        }
        fn transfer_from(
            &mut self,
            from: ActorId,
            to: ActorId,
            id: u128,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::TransferFrom, Self::Env> {
            self.pending_call((from, to, id, amount))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(Approve (operator: ActorId) -> bool | String, 0, <super::VmtImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(BalanceOf (account: ActorId, id: u128) -> u128 | String, 1, <super::VmtImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(BatchTransferFrom (from: ActorId, to: ActorId, ids: Vec<u128>, amounts: Vec<u128>) -> () | String, 2, <super::VmtImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(BcrstTokenId () -> u128 | String, 3, <super::VmtImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(BurnForRedeem (redeem_id: u128, owner: ActorId, scrst: u128, bcrst: u128, hcrst: u128) -> () | String, 4, <super::VmtImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Decimals () -> u128 | String, 5, <super::VmtImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(HcrstTokenId () -> u128 | String, 6, <super::VmtImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(IsApproved (account: ActorId, operator: ActorId) -> bool | String, 7, <super::VmtImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(MintResources (to: ActorId, scrst: u128, bcrst: u128, hcrst: u128) -> () | String, 8, <super::VmtImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Name () -> String | String, 9, <super::VmtImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(ScrstTokenId () -> u128 | String, 10, <super::VmtImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Symbol () -> String | String, 11, <super::VmtImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(TotalSupplyOf (id: u128) -> u128 | String, 12, <super::VmtImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(TransferFrom (from: ActorId, to: ActorId, id: u128, amount: u128) -> () | String, 13, <super::VmtImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[sails_rs::sails_type(crate = sails_rs)]
        #[derive(PartialEq, Debug)]
        pub enum VmtEvents {
            #[codec(index = 0)]
            Approval([u8; 32], [u8; 32]),
            #[codec(index = 1)]
            BatchTransfer([u8; 32], [u8; 32]),
            #[codec(index = 2)]
            Burned([u8; 32], u128, u128, u128),
            #[codec(index = 3)]
            Minted([u8; 32], u128, u128, u128),
            #[codec(index = 4)]
            RedeemBurnRejected(u128, [u8; 32], u128, u128, u128),
            #[codec(index = 5)]
            Transfer([u8; 32], [u8; 32], u128, u128),
        }

        impl VmtEvents {
            pub fn entry_id(&self) -> u16 {
                match self {
                    Self::Approval { .. } => 0,
                    Self::BatchTransfer { .. } => 1,
                    Self::Burned { .. } => 2,
                    Self::Minted { .. } => 3,
                    Self::RedeemBurnRejected { .. } => 4,
                    Self::Transfer { .. } => 5,
                }
            }
        }

        impl sails_rs::client::Event for VmtEvents {
            fn decode_event(
                route: &sails_rs::client::RouteIdx,
                payload: impl AsRef<[u8]>,
            ) -> Result<Self, sails_rs::scale_codec::Error> {
                sails_rs::client::decode_event_v2::<Self>(route.0, payload)
            }
        }

        impl sails_rs::client::Identifiable for VmtEvents {
            const INTERFACE_ID: sails_rs::InterfaceId =
                <VmtImpl as sails_rs::client::Identifiable>::INTERFACE_ID;
        }

        impl sails_rs::client::ServiceWithEvents for VmtImpl {
            type Event = VmtEvents;
        }
    }
}

pub mod admin {
    use super::*;

    pub trait Admin {
        type Env: sails_rs::client::GearEnv;
        fn add_admin(
            &mut self,
            admin: ActorId,
        ) -> sails_rs::client::PendingCall<io::AddAdmin, Self::Env>;
        fn add_minter(
            &mut self,
            minter: ActorId,
        ) -> sails_rs::client::PendingCall<io::AddMinter, Self::Env>;
        fn admins(&self) -> sails_rs::client::PendingCall<io::Admins, Self::Env>;
        fn is_admin(
            &self,
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::IsAdmin, Self::Env>;
        fn is_minter(
            &self,
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::IsMinter, Self::Env>;
        fn is_paused(&self) -> sails_rs::client::PendingCall<io::IsPaused, Self::Env>;
        fn minters(&self) -> sails_rs::client::PendingCall<io::Minters, Self::Env>;
        fn pause(&mut self) -> sails_rs::client::PendingCall<io::Pause, Self::Env>;
        fn redeem_contract(&self) -> sails_rs::client::PendingCall<io::RedeemContract, Self::Env>;
        fn remove_admin(
            &mut self,
            admin: ActorId,
        ) -> sails_rs::client::PendingCall<io::RemoveAdmin, Self::Env>;
        fn remove_minter(
            &mut self,
            minter: ActorId,
        ) -> sails_rs::client::PendingCall<io::RemoveMinter, Self::Env>;
        fn set_redeem_contract(
            &mut self,
            redeem_contract: ActorId,
        ) -> sails_rs::client::PendingCall<io::SetRedeemContract, Self::Env>;
        fn unpause(&mut self) -> sails_rs::client::PendingCall<io::Unpause, Self::Env>;
    }

    pub struct AdminImpl;

    impl sails_rs::client::Identifiable for AdminImpl {
        const INTERFACE_ID: sails_rs::InterfaceId =
            sails_rs::InterfaceId::from_bytes_8([1, 215, 149, 129, 235, 107, 148, 5]);
    }

    impl<E: sails_rs::client::GearEnv> Admin for sails_rs::client::Service<AdminImpl, E> {
        type Env = E;
        fn add_admin(
            &mut self,
            admin: ActorId,
        ) -> sails_rs::client::PendingCall<io::AddAdmin, Self::Env> {
            self.pending_call((admin,))
        }
        fn add_minter(
            &mut self,
            minter: ActorId,
        ) -> sails_rs::client::PendingCall<io::AddMinter, Self::Env> {
            self.pending_call((minter,))
        }
        fn admins(&self) -> sails_rs::client::PendingCall<io::Admins, Self::Env> {
            self.pending_call(())
        }
        fn is_admin(
            &self,
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::IsAdmin, Self::Env> {
            self.pending_call((account,))
        }
        fn is_minter(
            &self,
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::IsMinter, Self::Env> {
            self.pending_call((account,))
        }
        fn is_paused(&self) -> sails_rs::client::PendingCall<io::IsPaused, Self::Env> {
            self.pending_call(())
        }
        fn minters(&self) -> sails_rs::client::PendingCall<io::Minters, Self::Env> {
            self.pending_call(())
        }
        fn pause(&mut self) -> sails_rs::client::PendingCall<io::Pause, Self::Env> {
            self.pending_call(())
        }
        fn redeem_contract(&self) -> sails_rs::client::PendingCall<io::RedeemContract, Self::Env> {
            self.pending_call(())
        }
        fn remove_admin(
            &mut self,
            admin: ActorId,
        ) -> sails_rs::client::PendingCall<io::RemoveAdmin, Self::Env> {
            self.pending_call((admin,))
        }
        fn remove_minter(
            &mut self,
            minter: ActorId,
        ) -> sails_rs::client::PendingCall<io::RemoveMinter, Self::Env> {
            self.pending_call((minter,))
        }
        fn set_redeem_contract(
            &mut self,
            redeem_contract: ActorId,
        ) -> sails_rs::client::PendingCall<io::SetRedeemContract, Self::Env> {
            self.pending_call((redeem_contract,))
        }
        fn unpause(&mut self) -> sails_rs::client::PendingCall<io::Unpause, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(AddAdmin (admin: ActorId) -> bool | String, 0, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(AddMinter (minter: ActorId) -> bool | String, 1, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Admins () -> Vec<ActorId> | String, 2, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(IsAdmin (account: ActorId) -> bool | String, 3, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(IsMinter (account: ActorId) -> bool | String, 4, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(IsPaused () -> bool | String, 5, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Minters () -> Vec<ActorId> | String, 6, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Pause () -> () | String, 7, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(RedeemContract () -> ActorId | String, 8, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(RemoveAdmin (admin: ActorId) -> bool | String, 9, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(RemoveMinter (minter: ActorId) -> bool | String, 10, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(SetRedeemContract (redeem_contract: ActorId) -> () | String, 11, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Unpause () -> () | String, 12, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[sails_rs::sails_type(crate = sails_rs)]
        #[derive(PartialEq, Debug)]
        pub enum AdminEvents {
            #[codec(index = 0)]
            AdminAdded([u8; 32]),
            #[codec(index = 1)]
            AdminRemoved([u8; 32]),
            #[codec(index = 2)]
            MinterAdded([u8; 32]),
            #[codec(index = 3)]
            MinterRemoved([u8; 32]),
            #[codec(index = 4)]
            Paused([u8; 32]),
            #[codec(index = 5)]
            RedeemContractUpdated([u8; 32], [u8; 32]),
            #[codec(index = 6)]
            Unpaused([u8; 32]),
        }

        impl AdminEvents {
            pub fn entry_id(&self) -> u16 {
                match self {
                    Self::AdminAdded { .. } => 0,
                    Self::AdminRemoved { .. } => 1,
                    Self::MinterAdded { .. } => 2,
                    Self::MinterRemoved { .. } => 3,
                    Self::Paused { .. } => 4,
                    Self::RedeemContractUpdated { .. } => 5,
                    Self::Unpaused { .. } => 6,
                }
            }
        }

        impl sails_rs::client::Event for AdminEvents {
            fn decode_event(
                route: &sails_rs::client::RouteIdx,
                payload: impl AsRef<[u8]>,
            ) -> Result<Self, sails_rs::scale_codec::Error> {
                sails_rs::client::decode_event_v2::<Self>(route.0, payload)
            }
        }

        impl sails_rs::client::Identifiable for AdminEvents {
            const INTERFACE_ID: sails_rs::InterfaceId =
                <AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID;
        }

        impl sails_rs::client::ServiceWithEvents for AdminImpl {
            type Event = AdminEvents;
        }
    }
}
