// Code generated by sails-client-gen-v2. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct DiggerRedeemClientProgram;

impl DiggerRedeemClientProgram {
    pub const ROUTE_ID_REDEEM: u8 = 1;
    pub const ROUTE_ID_ADMIN: u8 = 2;
}

impl sails_rs::client::Program for DiggerRedeemClientProgram {}

pub trait DiggerRedeemClient {
    type Env: sails_rs::client::GearEnv;
    fn redeem(&self) -> sails_rs::client::Service<redeem::RedeemImpl, Self::Env>;
    fn admin(&self) -> sails_rs::client::Service<admin::AdminImpl, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> DiggerRedeemClient
    for sails_rs::client::Actor<DiggerRedeemClientProgram, E>
{
    type Env = E;
    fn redeem(&self) -> sails_rs::client::Service<redeem::RedeemImpl, Self::Env> {
        self.service(DiggerRedeemClientProgram::ROUTE_ID_REDEEM)
    }
    fn admin(&self) -> sails_rs::client::Service<admin::AdminImpl, Self::Env> {
        self.service(DiggerRedeemClientProgram::ROUTE_ID_ADMIN)
    }
}
pub trait DiggerRedeemClientCtors {
    type Env: sails_rs::client::GearEnv;
    fn create(
        self,
        res_contract: ActorId,
        vara_unit: u128,
        scrst_rate: u128,
        bcrst_rate: u128,
        hcrst_rate: u128,
    ) -> sails_rs::client::PendingCtor<DiggerRedeemClientProgram, io::Create, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> DiggerRedeemClientCtors
    for sails_rs::client::Deployment<DiggerRedeemClientProgram, E>
{
    type Env = E;
    fn create(
        self,
        res_contract: ActorId,
        vara_unit: u128,
        scrst_rate: u128,
        bcrst_rate: u128,
        hcrst_rate: u128,
    ) -> sails_rs::client::PendingCtor<DiggerRedeemClientProgram, io::Create, Self::Env> {
        self.pending_ctor((res_contract, vara_unit, scrst_rate, bcrst_rate, hcrst_rate))
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Create (res_contract: ActorId, vara_unit: u128, scrst_rate: u128, bcrst_rate: u128, hcrst_rate: u128) -> (), 0);
}

pub mod redeem {
    use super::*;

    pub trait Redeem {
        type Env: sails_rs::client::GearEnv;
        fn available_reserve(
            &self,
        ) -> sails_rs::client::PendingCall<io::AvailableReserve, Self::Env>;
        fn bcrst_rate(&self) -> sails_rs::client::PendingCall<io::BcrstRate, Self::Env>;
        fn cancel_redeem(
            &mut self,
            redeem_id: u128,
        ) -> sails_rs::client::PendingCall<io::CancelRedeem, Self::Env>;
        fn confirm_redeem(
            &mut self,
            redeem_id: u128,
        ) -> sails_rs::client::PendingCall<io::ConfirmRedeem, Self::Env>;
        fn deposit_reserve(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::DepositReserve, Self::Env>;
        fn hcrst_rate(&self) -> sails_rs::client::PendingCall<io::HcrstRate, Self::Env>;
        fn locked_balance(&self) -> sails_rs::client::PendingCall<io::LockedBalance, Self::Env>;
        fn pending_redeem_count(
            &self,
        ) -> sails_rs::client::PendingCall<io::PendingRedeemCount, Self::Env>;
        fn redeem(
            &mut self,
            scrst: u128,
            bcrst: u128,
            hcrst: u128,
        ) -> sails_rs::client::PendingCall<io::Redeem, Self::Env>;
        fn reserve_balance(&self) -> sails_rs::client::PendingCall<io::ReserveBalance, Self::Env>;
        fn scrst_rate(&self) -> sails_rs::client::PendingCall<io::ScrstRate, Self::Env>;
        fn total_paid(&self) -> sails_rs::client::PendingCall<io::TotalPaid, Self::Env>;
        fn total_redeemed_bcrst(
            &self,
        ) -> sails_rs::client::PendingCall<io::TotalRedeemedBcrst, Self::Env>;
        fn total_redeemed_hcrst(
            &self,
        ) -> sails_rs::client::PendingCall<io::TotalRedeemedHcrst, Self::Env>;
        fn total_redeemed_scrst(
            &self,
        ) -> sails_rs::client::PendingCall<io::TotalRedeemedScrst, Self::Env>;
        fn vara_unit(&self) -> sails_rs::client::PendingCall<io::VaraUnit, Self::Env>;
    }

    pub struct RedeemImpl;

    impl sails_rs::client::Identifiable for RedeemImpl {
        const INTERFACE_ID: sails_rs::InterfaceId =
            sails_rs::InterfaceId::from_bytes_8([116, 192, 67, 47, 159, 23, 46, 21]);
    }

    impl<E: sails_rs::client::GearEnv> Redeem for sails_rs::client::Service<RedeemImpl, E> {
        type Env = E;
        fn available_reserve(
            &self,
        ) -> sails_rs::client::PendingCall<io::AvailableReserve, Self::Env> {
            self.pending_call(())
        }
        fn bcrst_rate(&self) -> sails_rs::client::PendingCall<io::BcrstRate, Self::Env> {
            self.pending_call(())
        }
        fn cancel_redeem(
            &mut self,
            redeem_id: u128,
        ) -> sails_rs::client::PendingCall<io::CancelRedeem, Self::Env> {
            self.pending_call((redeem_id,))
        }
        fn confirm_redeem(
            &mut self,
            redeem_id: u128,
        ) -> sails_rs::client::PendingCall<io::ConfirmRedeem, Self::Env> {
            self.pending_call((redeem_id,))
        }
        fn deposit_reserve(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::DepositReserve, Self::Env> {
            self.pending_call(())
        }
        fn hcrst_rate(&self) -> sails_rs::client::PendingCall<io::HcrstRate, Self::Env> {
            self.pending_call(())
        }
        fn locked_balance(&self) -> sails_rs::client::PendingCall<io::LockedBalance, Self::Env> {
            self.pending_call(())
        }
        fn pending_redeem_count(
            &self,
        ) -> sails_rs::client::PendingCall<io::PendingRedeemCount, Self::Env> {
            self.pending_call(())
        }
        fn redeem(
            &mut self,
            scrst: u128,
            bcrst: u128,
            hcrst: u128,
        ) -> sails_rs::client::PendingCall<io::Redeem, Self::Env> {
            self.pending_call((scrst, bcrst, hcrst))
        }
        fn reserve_balance(&self) -> sails_rs::client::PendingCall<io::ReserveBalance, Self::Env> {
            self.pending_call(())
        }
        fn scrst_rate(&self) -> sails_rs::client::PendingCall<io::ScrstRate, Self::Env> {
            self.pending_call(())
        }
        fn total_paid(&self) -> sails_rs::client::PendingCall<io::TotalPaid, Self::Env> {
            self.pending_call(())
        }
        fn total_redeemed_bcrst(
            &self,
        ) -> sails_rs::client::PendingCall<io::TotalRedeemedBcrst, Self::Env> {
            self.pending_call(())
        }
        fn total_redeemed_hcrst(
            &self,
        ) -> sails_rs::client::PendingCall<io::TotalRedeemedHcrst, Self::Env> {
            self.pending_call(())
        }
        fn total_redeemed_scrst(
            &self,
        ) -> sails_rs::client::PendingCall<io::TotalRedeemedScrst, Self::Env> {
            self.pending_call(())
        }
        fn vara_unit(&self) -> sails_rs::client::PendingCall<io::VaraUnit, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(AvailableReserve () -> u128 | String, 0, <super::RedeemImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(BcrstRate () -> u128 | String, 1, <super::RedeemImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(CancelRedeem (redeem_id: u128) -> () | String, 2, <super::RedeemImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(ConfirmRedeem (redeem_id: u128) -> u128 | String, 3, <super::RedeemImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(DepositReserve () -> u128 | String, 4, <super::RedeemImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(HcrstRate () -> u128 | String, 5, <super::RedeemImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(LockedBalance () -> u128 | String, 6, <super::RedeemImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(PendingRedeemCount () -> u128 | String, 7, <super::RedeemImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Redeem (scrst: u128, bcrst: u128, hcrst: u128) -> u128 | String, 8, <super::RedeemImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(ReserveBalance () -> u128 | String, 9, <super::RedeemImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(ScrstRate () -> u128 | String, 10, <super::RedeemImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(TotalPaid () -> u128 | String, 11, <super::RedeemImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(TotalRedeemedBcrst () -> u128 | String, 12, <super::RedeemImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(TotalRedeemedHcrst () -> u128 | String, 13, <super::RedeemImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(TotalRedeemedScrst () -> u128 | String, 14, <super::RedeemImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(VaraUnit () -> u128 | String, 15, <super::RedeemImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[sails_rs::sails_type(crate = sails_rs)]
        #[derive(PartialEq, Debug)]
        pub enum RedeemEvents {
            #[codec(index = 0)]
            RedeemCanceled(u128, [u8; 32], u128, u128, u128, u128),
            #[codec(index = 1)]
            Redeemed([u8; 32], u128, u128, u128, u128),
            #[codec(index = 2)]
            RedeemRequested(u128, [u8; 32], u128, u128, u128, u128),
            #[codec(index = 3)]
            ReserveDeposited([u8; 32], u128, u128),
            #[codec(index = 4)]
            ReserveSynced(u128, u128),
        }

        impl RedeemEvents {
            pub fn entry_id(&self) -> u16 {
                match self {
                    Self::RedeemCanceled { .. } => 0,
                    Self::Redeemed { .. } => 1,
                    Self::RedeemRequested { .. } => 2,
                    Self::ReserveDeposited { .. } => 3,
                    Self::ReserveSynced { .. } => 4,
                }
            }
        }

        impl sails_rs::client::Event for RedeemEvents {
            fn decode_event(
                route: &sails_rs::client::RouteIdx,
                payload: impl AsRef<[u8]>,
            ) -> Result<Self, sails_rs::scale_codec::Error> {
                sails_rs::client::decode_event_v2::<Self>(route.0, payload)
            }
        }

        impl sails_rs::client::Identifiable for RedeemEvents {
            const INTERFACE_ID: sails_rs::InterfaceId =
                <RedeemImpl as sails_rs::client::Identifiable>::INTERFACE_ID;
        }

        impl sails_rs::client::ServiceWithEvents for RedeemImpl {
            type Event = RedeemEvents;
        }
    }
}

pub mod admin {
    use super::*;

    pub trait Admin {
        type Env: sails_rs::client::GearEnv;
        fn add_admin(
            &mut self,
            admin: ActorId,
        ) -> sails_rs::client::PendingCall<io::AddAdmin, Self::Env>;
        fn admins(&self) -> sails_rs::client::PendingCall<io::Admins, Self::Env>;
        fn is_admin(
            &self,
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::IsAdmin, Self::Env>;
        fn is_paused(&self) -> sails_rs::client::PendingCall<io::IsPaused, Self::Env>;
        fn pause(&mut self) -> sails_rs::client::PendingCall<io::Pause, Self::Env>;
        fn remove_admin(
            &mut self,
            admin: ActorId,
        ) -> sails_rs::client::PendingCall<io::RemoveAdmin, Self::Env>;
        fn res_contract(&self) -> sails_rs::client::PendingCall<io::ResContract, Self::Env>;
        fn set_rate_config(
            &mut self,
            vara_unit: u128,
            scrst_rate: u128,
            bcrst_rate: u128,
            hcrst_rate: u128,
        ) -> sails_rs::client::PendingCall<io::SetRateConfig, Self::Env>;
        fn set_rates(
            &mut self,
            scrst_rate: u128,
            bcrst_rate: u128,
            hcrst_rate: u128,
        ) -> sails_rs::client::PendingCall<io::SetRates, Self::Env>;
        fn set_res_contract(
            &mut self,
            res_contract: ActorId,
        ) -> sails_rs::client::PendingCall<io::SetResContract, Self::Env>;
        fn unpause(&mut self) -> sails_rs::client::PendingCall<io::Unpause, Self::Env>;
        fn withdraw_funds(
            &mut self,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::WithdrawFunds, Self::Env>;
    }

    pub struct AdminImpl;

    impl sails_rs::client::Identifiable for AdminImpl {
        const INTERFACE_ID: sails_rs::InterfaceId =
            sails_rs::InterfaceId::from_bytes_8([48, 166, 228, 163, 224, 67, 46, 69]);
    }

    impl<E: sails_rs::client::GearEnv> Admin for sails_rs::client::Service<AdminImpl, E> {
        type Env = E;
        fn add_admin(
            &mut self,
            admin: ActorId,
        ) -> sails_rs::client::PendingCall<io::AddAdmin, Self::Env> {
            self.pending_call((admin,))
        }
        fn admins(&self) -> sails_rs::client::PendingCall<io::Admins, Self::Env> {
            self.pending_call(())
        }
        fn is_admin(
            &self,
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::IsAdmin, Self::Env> {
            self.pending_call((account,))
        }
        fn is_paused(&self) -> sails_rs::client::PendingCall<io::IsPaused, Self::Env> {
            self.pending_call(())
        }
        fn pause(&mut self) -> sails_rs::client::PendingCall<io::Pause, Self::Env> {
            self.pending_call(())
        }
        fn remove_admin(
            &mut self,
            admin: ActorId,
        ) -> sails_rs::client::PendingCall<io::RemoveAdmin, Self::Env> {
            self.pending_call((admin,))
        }
        fn res_contract(&self) -> sails_rs::client::PendingCall<io::ResContract, Self::Env> {
            self.pending_call(())
        }
        fn set_rate_config(
            &mut self,
            vara_unit: u128,
            scrst_rate: u128,
            bcrst_rate: u128,
            hcrst_rate: u128,
        ) -> sails_rs::client::PendingCall<io::SetRateConfig, Self::Env> {
            self.pending_call((vara_unit, scrst_rate, bcrst_rate, hcrst_rate))
        }
        fn set_rates(
            &mut self,
            scrst_rate: u128,
            bcrst_rate: u128,
            hcrst_rate: u128,
        ) -> sails_rs::client::PendingCall<io::SetRates, Self::Env> {
            self.pending_call((scrst_rate, bcrst_rate, hcrst_rate))
        }
        fn set_res_contract(
            &mut self,
            res_contract: ActorId,
        ) -> sails_rs::client::PendingCall<io::SetResContract, Self::Env> {
            self.pending_call((res_contract,))
        }
        fn unpause(&mut self) -> sails_rs::client::PendingCall<io::Unpause, Self::Env> {
            self.pending_call(())
        }
        fn withdraw_funds(
            &mut self,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::WithdrawFunds, Self::Env> {
            self.pending_call((amount,))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(AddAdmin (admin: ActorId) -> bool | String, 0, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Admins () -> Vec<ActorId> | String, 1, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(IsAdmin (account: ActorId) -> bool | String, 2, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(IsPaused () -> bool | String, 3, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Pause () -> () | String, 4, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(RemoveAdmin (admin: ActorId) -> bool | String, 5, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(ResContract () -> ActorId | String, 6, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(SetRateConfig (vara_unit: u128, scrst_rate: u128, bcrst_rate: u128, hcrst_rate: u128) -> () | String, 7, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(SetRates (scrst_rate: u128, bcrst_rate: u128, hcrst_rate: u128) -> () | String, 8, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(SetResContract (res_contract: ActorId) -> () | String, 9, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Unpause () -> () | String, 10, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(WithdrawFunds (amount: u128) -> () | String, 11, <super::AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[sails_rs::sails_type(crate = sails_rs)]
        #[derive(PartialEq, Debug)]
        pub enum AdminEvents {
            #[codec(index = 0)]
            AdminAdded([u8; 32]),
            #[codec(index = 1)]
            AdminRemoved([u8; 32]),
            #[codec(index = 2)]
            FundsWithdrawn([u8; 32], u128, u128),
            #[codec(index = 3)]
            Paused([u8; 32]),
            #[codec(index = 4)]
            RateConfigUpdated(u128, u128, u128, u128),
            #[codec(index = 5)]
            RatesUpdated(u128, u128, u128),
            #[codec(index = 6)]
            ResContractUpdated([u8; 32], [u8; 32]),
            #[codec(index = 7)]
            Unpaused([u8; 32]),
        }

        impl AdminEvents {
            pub fn entry_id(&self) -> u16 {
                match self {
                    Self::AdminAdded { .. } => 0,
                    Self::AdminRemoved { .. } => 1,
                    Self::FundsWithdrawn { .. } => 2,
                    Self::Paused { .. } => 3,
                    Self::RateConfigUpdated { .. } => 4,
                    Self::RatesUpdated { .. } => 5,
                    Self::ResContractUpdated { .. } => 6,
                    Self::Unpaused { .. } => 7,
                }
            }
        }

        impl sails_rs::client::Event for AdminEvents {
            fn decode_event(
                route: &sails_rs::client::RouteIdx,
                payload: impl AsRef<[u8]>,
            ) -> Result<Self, sails_rs::scale_codec::Error> {
                sails_rs::client::decode_event_v2::<Self>(route.0, payload)
            }
        }

        impl sails_rs::client::Identifiable for AdminEvents {
            const INTERFACE_ID: sails_rs::InterfaceId =
                <AdminImpl as sails_rs::client::Identifiable>::INTERFACE_ID;
        }

        impl sails_rs::client::ServiceWithEvents for AdminImpl {
            type Event = AdminEvents;
        }
    }
}
