// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct LuisaProofRouterClientProgram;

impl LuisaProofRouterClientProgram {
    pub const ROUTE_ID_PROOF_PACK: u8 = 1;
}

impl sails_rs::client::Program for LuisaProofRouterClientProgram {}

pub trait LuisaProofRouterClient {
    type Env: sails_rs::client::GearEnv;
    fn proof_pack(&self) -> sails_rs::client::Service<proof_pack::ProofPackImpl, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> LuisaProofRouterClient
    for sails_rs::client::Actor<LuisaProofRouterClientProgram, E>
{
    type Env = E;
    fn proof_pack(&self) -> sails_rs::client::Service<proof_pack::ProofPackImpl, Self::Env> {
        self.service(LuisaProofRouterClientProgram::ROUTE_ID_PROOF_PACK)
    }
}
pub trait LuisaProofRouterClientCtors {
    type Env: sails_rs::client::GearEnv;
    fn create(
        self,
    ) -> sails_rs::client::PendingCtor<LuisaProofRouterClientProgram, io::Create, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> LuisaProofRouterClientCtors
    for sails_rs::client::Deployment<LuisaProofRouterClientProgram, E>
{
    type Env = E;
    fn create(
        self,
    ) -> sails_rs::client::PendingCtor<LuisaProofRouterClientProgram, io::Create, Self::Env> {
        self.pending_ctor(())
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Create () -> (), 0);
}

pub mod proof_pack {
    use super::*;

    #[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo, ReflectHash)]
    #[codec(crate = sails_rs::scale_codec)]
    #[scale_info(crate = sails_rs::scale_info)]
    #[reflect_hash(crate = sails_rs)]
    pub struct ProofReceipt {
        pub id: u128,
        pub submitter: ActorId,
        pub subject_app: ActorId,
        pub target_app: ActorId,
        pub proof_kind: String,
        pub proof_tx_hash: String,
        pub evidence_hash: String,
        pub external_ref: String,
        pub summary: String,
    }

    pub trait ProofPack {
        type Env: sails_rs::client::GearEnv;
        fn get_receipt(&self, id: u128)
        -> sails_rs::client::PendingCall<io::GetReceipt, Self::Env>;
        fn is_paused(&self) -> sails_rs::client::PendingCall<io::IsPaused, Self::Env>;
        fn owner(&self) -> sails_rs::client::PendingCall<io::Owner, Self::Env>;
        fn pause(&mut self) -> sails_rs::client::PendingCall<io::Pause, Self::Env>;
        fn receipt_count(&self) -> sails_rs::client::PendingCall<io::ReceiptCount, Self::Env>;
        fn receipts_for_subject(
            &self,
            subject_app: ActorId,
        ) -> sails_rs::client::PendingCall<io::ReceiptsForSubject, Self::Env>;
        fn receipts_for_target(
            &self,
            target_app: ActorId,
        ) -> sails_rs::client::PendingCall<io::ReceiptsForTarget, Self::Env>;
        fn recent_receipts(
            &self,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::RecentReceipts, Self::Env>;
        fn submit_receipt(
            &mut self,
            subject_app: ActorId,
            target_app: ActorId,
            proof_kind: String,
            proof_tx_hash: String,
            evidence_hash: String,
            external_ref: String,
            summary: String,
        ) -> sails_rs::client::PendingCall<io::SubmitReceipt, Self::Env>;
        fn unpause(&mut self) -> sails_rs::client::PendingCall<io::Unpause, Self::Env>;
    }

    pub struct ProofPackImpl;

    impl sails_rs::client::Identifiable for ProofPackImpl {
        const INTERFACE_ID: sails_rs::InterfaceId =
            sails_rs::InterfaceId::from_bytes_8([241, 33, 170, 219, 166, 169, 134, 80]);
    }

    impl<E: sails_rs::client::GearEnv> ProofPack for sails_rs::client::Service<ProofPackImpl, E> {
        type Env = E;
        fn get_receipt(
            &self,
            id: u128,
        ) -> sails_rs::client::PendingCall<io::GetReceipt, Self::Env> {
            self.pending_call((id,))
        }
        fn is_paused(&self) -> sails_rs::client::PendingCall<io::IsPaused, Self::Env> {
            self.pending_call(())
        }
        fn owner(&self) -> sails_rs::client::PendingCall<io::Owner, Self::Env> {
            self.pending_call(())
        }
        fn pause(&mut self) -> sails_rs::client::PendingCall<io::Pause, Self::Env> {
            self.pending_call(())
        }
        fn receipt_count(&self) -> sails_rs::client::PendingCall<io::ReceiptCount, Self::Env> {
            self.pending_call(())
        }
        fn receipts_for_subject(
            &self,
            subject_app: ActorId,
        ) -> sails_rs::client::PendingCall<io::ReceiptsForSubject, Self::Env> {
            self.pending_call((subject_app,))
        }
        fn receipts_for_target(
            &self,
            target_app: ActorId,
        ) -> sails_rs::client::PendingCall<io::ReceiptsForTarget, Self::Env> {
            self.pending_call((target_app,))
        }
        fn recent_receipts(
            &self,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::RecentReceipts, Self::Env> {
            self.pending_call((limit,))
        }
        fn submit_receipt(
            &mut self,
            subject_app: ActorId,
            target_app: ActorId,
            proof_kind: String,
            proof_tx_hash: String,
            evidence_hash: String,
            external_ref: String,
            summary: String,
        ) -> sails_rs::client::PendingCall<io::SubmitReceipt, Self::Env> {
            self.pending_call((
                subject_app,
                target_app,
                proof_kind,
                proof_tx_hash,
                evidence_hash,
                external_ref,
                summary,
            ))
        }
        fn unpause(&mut self) -> sails_rs::client::PendingCall<io::Unpause, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(GetReceipt (id: u128) -> super::Option<super::ProofReceipt, >, 0, <super::ProofPackImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(IsPaused () -> bool, 1, <super::ProofPackImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Owner () -> ActorId, 2, <super::ProofPackImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Pause () -> () | String, 3, <super::ProofPackImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(ReceiptCount () -> u128, 4, <super::ProofPackImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(ReceiptsForSubject (subject_app: ActorId) -> Vec<u128>, 5, <super::ProofPackImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(ReceiptsForTarget (target_app: ActorId) -> Vec<u128>, 6, <super::ProofPackImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(RecentReceipts (limit: u32) -> Vec<super::ProofReceipt>, 7, <super::ProofPackImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(SubmitReceipt (subject_app: ActorId, target_app: ActorId, proof_kind: String, proof_tx_hash: String, evidence_hash: String, external_ref: String, summary: String) -> super::ProofReceipt | String, 8, <super::ProofPackImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Unpause () -> () | String, 9, <super::ProofPackImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode, ReflectHash)]
        #[codec(crate = sails_rs::scale_codec)]
        #[reflect_hash(crate = sails_rs)]
        pub enum ProofPackEvents {
            #[codec(index = 0)]
            Paused([u8; 32]),
            #[codec(index = 1)]
            ReceiptSubmitted(u128, [u8; 32], [u8; 32], [u8; 32], String, String, String),
            #[codec(index = 2)]
            Unpaused([u8; 32]),
        }

        impl ProofPackEvents {
            pub fn entry_id(&self) -> u16 {
                match self {
                    Self::Paused { .. } => 0,
                    Self::ReceiptSubmitted { .. } => 1,
                    Self::Unpaused { .. } => 2,
                }
            }
        }

        impl sails_rs::client::Event for ProofPackEvents {}

        impl sails_rs::client::Identifiable for ProofPackEvents {
            const INTERFACE_ID: sails_rs::InterfaceId =
                <ProofPackImpl as sails_rs::client::Identifiable>::INTERFACE_ID;
        }

        impl sails_rs::client::ServiceWithEvents for ProofPackImpl {
            type Event = ProofPackEvents;
        }
    }
}
