
!@sails: 1.0.0-beta.5

service World@0xc63310d77006e90d {
    events {
        AgentDied(u64, [u8; 32], u32, u32, u32),
        AgentExited(u64, [u8; 32]),
        AgentMoved(u64, [u8; 32], u32, u32, u32, u32),
        AgentRegistered(u64, [u8; 32]),
        AgentSpawned(u64, [u8; 32], u32, u32),
        AgentSurfaced(u64, [u8; 32], u32, u32, u32),
        ChestOpened(u64, [u8; 32], u32, u32, u32, u32),
        LadderPlaced(u64, [u8; 32], u32, u32, u32),
        ResourceExtracted(u64, [u8; 32], u32, u32, u32, u32),
        ResourcesMinted(u64, [u8; 32], u32, u32, u32),
        ResourcesTradedForLadders(u64, [u8; 32], u32, u32, u32, u32, u32),
        SessionStarted(u64),
        StoneMoved(u64, [u8; 32], u32, u32, u32, u32),
        TileDrilled(u64, [u8; 32], u32, u32, u32, u32),
    }
    functions {
        @query
        AgentOf(owner: ActorId) -> [u128] throws String;
        @query
        Agents() -> [ActorId] throws String;
        @query
        Config() -> [u32] throws String;
        Drill(direction: u32) -> [u128] throws String;
        Exit() -> [u128] throws String;
        @query
        InventoryOf(owner: ActorId) -> [u32] throws String;
        @query
        IsDug(x: u32, y: u32) -> bool throws String;
        @query
        MapSnapshot() -> [u32] throws String;
        MintResources() -> [u128] throws String;
        MoveAgent(direction: u32) -> [u128] throws String;
        @query
        OwnerOf(proxy: ActorId) -> ActorId throws String;
        PlaceLadder(direction: u32) -> [u128] throws String;
        Register(owner: ActorId) -> [u128] throws String;
        @query
        Session() -> [u128] throws String;
        Surface() -> [u128] throws String;
        @query
        TileAt(x: u32, y: u32) -> u32 throws String;
        TradeResourcesForLadders(scrst: u32, bcrst: u32, hcrst: u32) -> [u128] throws String;
    }
}

service Admin@0x5acb75662050b164 {
    events {
        Killed([u8; 32]),
        MapGenerated(u64, u64),
        ResourceVmtUpdated([u8; 32], [u8; 32]),
        SessionFinished(u64),
        SessionStarted(u64),
    }
    functions {
        @query
        Admin() -> ActorId throws String;
        FinishSession() -> [u128] throws String;
        Kill(inheritor: ActorId) throws String;
        ResetMap(seed: u64) -> [u128] throws String;
        @query
        ResourceVmt() -> ActorId throws String;
        SetResourceVmt(resource_vmt: ActorId) -> ActorId throws String;
        StartSession() -> [u128] throws String;
        UploadMap(seed: u64, map: [u32]) -> [u128] throws String;
    }
}

program DiggerWorld {
    constructors {
        Create();
    }
    services {
        World@0xc63310d77006e90d,
        Admin@0x5acb75662050b164,
    }
}
