[package]
name = "digger-proxy"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Per-agent Digger proxy program Wasm and IDL package"
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
sails-rs = { workspace = true, features = ["ethexe"] }
digger-proxy-app.workspace = true

[dev-dependencies]
sails-rs = { workspace = true, features = ["ethexe", "gtest", "gclient"] }
tokio = { workspace = true, features = ["rt", "macros"] }
digger-proxy-client.workspace = true
digger-world.workspace = true
digger-world-app.workspace = true
digger-world-client.workspace = true

[build-dependencies]
sails-rs = { workspace = true, features = ["ethexe", "build"] }
digger-proxy-app.workspace = true
